version: '3'
services:
  #  api:
  #    build:
  #      context: build-api
  #      args:
  #        - STAGE=${STAGE}
  #        - BRANCH=${BRANCH}
  #    env_file:
  #      - ./.env
  #    networks:
  #      - backend
  #    volumes:
  #      - ./../api/:${API_CODE_PATH_CONTAINER}

  #  web:
  #    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/web:${BRANCH}"
  #    build:
  #      context: ./build-web
  #      args:
  #        - WEB_REPO=${WEB_REPO}
  #        - WEB_CODE_PATH_CONTAINER=${WEB_CODE_PATH_CONTAINER}
  #        - STAGE=${STAGE}
  #        - BRANCH=${BRANCH}
  #    env_file:
  #      - ./.env
  #    networks:
  #      - frontend
  #    volumes:
  #      - ./../web/:${WEB_CODE_PATH_CONTAINER}


  ### PHP-FPM ##############################################
  php-fpm:
    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/php-fpm:${BRANCH}"
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_TAG=${PHP_TAG}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    extra_hosts:
      - "palantir.local:127.0.0.1"
    env_file:
      - ./.env
    networks:
      - backend

  ### NGINX Server #########################################
  nginx:
    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/nginx:${BRANCH}"
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    env_file:
      - ./.env

  ### MySQL Server #########################################
#  mysql:
#    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/mysql:${BRANCH}"
#    command: mysqld --default-authentication-plugin=mysql_native_password
#    build:
#      context: ./mysql
#      args:
#        - MYSQL_VERSION=${MYSQL_VERSION}
#    environment:
#      - MYSQL_VERSION=${MYSQL_VERSION}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - TZ=${WORKSPACE_TIMEZONE}
#    volumes:
#      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
#      - ${MYSQL_ENTRY_FILES_INITDB}:/docker-entrypoint-initdb.d
#    ports:
#      - "${MYSQL_PORT}:3306"
#    networks:
#      - backend

  ### PostgreSQL ###########################################
  postgres:
    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/postgres:${BRANCH}"
    build: ./postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}
#      - GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}
#      - GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}
#      - GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}
#      - JUPYTERHUB_POSTGRES_INIT=${JUPYTERHUB_POSTGRES_INIT}
#      - JUPYTERHUB_POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
#      - JUPYTERHUB_POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
#      - JUPYTERHUB_POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
#      - SONARQUBE_POSTGRES_INIT=${SONARQUBE_POSTGRES_INIT}
#      - SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}
#      - SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}
#      - SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}
#      - POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}
#      - POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}
#      - POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}
#      - POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.21.193.208/29
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.21.193.216/29
