version: '3'

volumes:
  api:
  web:

services:
  builder:
    image: "${COMPOSE_PROJECT_NAME}/${CONTEXT}/builder"
    build:
      context: ./builder
      args:
        - API_REPO=${API_REPO}
        - API_CODE_PATH_CONTAINER=${API_SOURCE_PATH}
        - CONTEXT=${CONTEXT}
        - BRANCH=${BRANCH}
    networks:
      - backend
      - frontend

  ### API ##############################################
  api:
    image: "${COMPOSE_PROJECT_NAME}/${CONTEXT}/api:${BRANCH}"
    build:
      context: build-api
      dockerfile: ./Dockerfile
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - API_REPO=${API_REPO}
        - API_CODE_PATH_CONTAINER=${API_VOLUME_PATH}
        - CONTEXT=${CONTEXT}
        - BRANCH=${BRANCH}
    volumes:
      - api:${API_VOLUME_PATH}
    networks:
      - backend
    depends_on:
      - builder

  ### WEB APPLICATION ##############################################
  web:
    image: "${COMPOSE_PROJECT_NAME}/${CONTEXT}/web:${BRANCH}"
    build:
      context: ./build-web
      dockerfile: ./Dockerfile
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - WEB_REPO=${WEB_REPO}
        - WEB_CODE_PATH_CONTAINER=${WEB_SOURCE_PATH}
        - CONTEXT=${CONTEXT}
        - BRANCH=${BRANCH}
    volumes:
      - web:${WEB_VOLUME_PATH}
    depends_on:
      - builder
    networks:
      - frontend

  ### PHP-FPM ##############################################
  php-fpm:
    volumes:
      - api:${API_VOLUME_PATH}
      - web:${WEB_VOLUME_PATH}
    depends_on:
      - api
      - web

  ### NGINX Server #########################################
  nginx:
#    environment:
#      - PRODUCTION_HOST=${PRODUCTION_HOST}
    volumes:
      - api:${API_VOLUME_PATH}
      - web:${WEB_VOLUME_PATH}
