version: '3'

services:
  ### DOCKER-WEB-UI ################################################
  #  docker-web-ui:
  #    build:
  #      context: ./docker-web-ui
  #    environment:
  #      - TZ=${WORKSPACE_TIMEZONE}
  #      - ENV_DOCKER_REGISTRY_HOST=${DOCKER_WEBUI_REGISTRY_HOST}
  #      - ENV_DOCKER_REGISTRY_PORT=${DOCKER_WEBUI_REGISTRY_PORT}
  #      - ENV_DOCKER_REGISTRY_USE_SSL=${DOCKER_REGISTRY_USE_SSL}
  #      - ENV_MODE_BROWSE_ONLY=${DOCKER_REGISTRY_BROWSE_ONLY}
  #    volumes:
  #      - /etc/localtime:/etc/localtime:ro
  #    ports:
  #      - "${DOCKER_WEBUI_PORT}:9090"
  #    networks:

  #  web:
  #    build:
  #      context: ./build-web
  #      dockerfile: /Dockerfile
  #      args:
  #        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
  #        - WEB_REPO=${WEB_REPO}
  #        - WEB_CONTAINER_PATH=${WEB_CONTAINER_PATH}
  #        - STAGE=${STAGE}
  #        - BRANCH=${BRANCH}
  #    env_file:
  #      - ./.env
  #    networks:
  #      - frontend
  #    volumes:
  #      - ../${WEB_SOURCE_PATH}:${WEB_CONTAINER_PATH}

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      args:
        - PRODUCTION=false
        - STAGE=${STAGE}
    volumes:
      - ${API_SOURCE_PATH}:${API_CONTAINER_PATH}
      - ${WEB_SOURCE_PATH}:${WEB_CONTAINER_PATH}
    depends_on:
      - workspace

  ### NGINX Server #########################################
  nginx:
    build:
      args:
        - PRODUCTION=false
        - STAGE=${STAGE}
    volumes:
      - ${API_SOURCE_PATH}:${API_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
      - ${WEB_SOURCE_PATH}:${WEB_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443


  ### Workspace Utilities ##################################
  workspace:
    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/workspace:${BRANCH}"
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
        - INSTALL_PHPDBG=${WORKSPACE_INSTALL_PHPDBG}
        - NVM_NODEJS_ORG_MIRROR=${WORKSPACE_NVM_NODEJS_ORG_MIRROR}
        - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
        - NPM_REGISTRY=${WORKSPACE_NPM_REGISTRY}
        - INSTALL_NPM_VUE_CLI=${WORKSPACE_INSTALL_NPM_VUE_CLI}
        - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
        - COMPOSER_AUTH=${WORKSPACE_COMPOSER_AUTH}
        - COMPOSER_REPO_PACKAGIST=${WORKSPACE_COMPOSER_REPO_PACKAGIST}
        - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
        - INSTALL_PRESTISSIMO=${WORKSPACE_INSTALL_PRESTISSIMO}
        - INSTALL_DUSK_DEPS=${WORKSPACE_INSTALL_DUSK_DEPS}
        - INSTALL_PG_CLIENT=${WORKSPACE_INSTALL_PG_CLIENT}
        - INSTALL_MYSQL_CLIENT=${WORKSPACE_INSTALL_MYSQL_CLIENT}
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - TZ=${WORKSPACE_TIMEZONE}
        - API_SOURCE_PATH=${API_SOURCE_PATH}
        - WEB_SOURCE_PATH=${WEB_SOURCE_PATH}
        - API_CONTAINER_PATH=${API_CONTAINER_PATH}
        - WEB_CONTAINER_PATH=${WEB_CONTAINER_PATH}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${API_SOURCE_PATH}:${API_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
      - ${WEB_SOURCE_PATH}:${WEB_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
      - ./php-worker/supervisord.d:/etc/supervisord.d
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "${COMPOSE_PROJECT_NAME}.local:0.0.0.0"
      - 9527:9527
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
#    command: npm run dev

#  ### PHP Worker ############################################
#  php-worker:
#    build:
#      context: ./php-worker
#      args:
#        - CHANGE_SOURCE=${CHANGE_SOURCE}
#        - PHP_VERSION=${PHP_VERSION}
#        - PHALCON_VERSION=${PHALCON_VERSION}
#        - INSTALL_PGSQL=${PHP_WORKER_INSTALL_PGSQL}
#        - INSTALL_BCMATH=${PHP_WORKER_INSTALL_BCMATH}
#        - INSTALL_PHALCON=${PHP_WORKER_INSTALL_PHALCON}
#        - INSTALL_SOAP=${PHP_WORKER_INSTALL_SOAP}
#        - INSTALL_ZIP_ARCHIVE=${PHP_WORKER_INSTALL_ZIP_ARCHIVE}
#        - INSTALL_MYSQL_CLIENT=${PHP_WORKER_INSTALL_MYSQL_CLIENT}
#        - INSTALL_AMQP=${PHP_WORKER_INSTALL_AMQP}
#        - INSTALL_CASSANDRA=${PHP_WORKER_INSTALL_CASSANDRA}
#        - INSTALL_GEARMAN=${PHP_WORKER_INSTALL_GEARMAN}
#        - INSTALL_GHOSTSCRIPT=${PHP_WORKER_INSTALL_GHOSTSCRIPT}
#        - INSTALL_SWOOLE=${PHP_WORKER_INSTALL_SWOOLE}
#        - INSTALL_TAINT=${PHP_WORKER_INSTALL_TAINT}
#        - INSTALL_FFMPEG=${PHP_WORKER_INSTALL_FFMPEG}
#        - INSTALL_GMP=${PHP_WORKER_INSTALL_GMP}
#        - INSTALL_REDIS=${PHP_WORKER_INSTALL_REDIS}
#        - PUID=${PHP_WORKER_PUID}
#        - PGID=${PHP_WORKER_PGID}
#    volumes:
#      - ${API_SOURCE_PATH}:${API_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
#      - ${WEB_SOURCE_PATH}:${WEB_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
#      - ./php-worker/supervisord.d:/etc/supervisord.d
#    depends_on:
#      - workspace
#    extra_hosts:
#      - "dockerhost:${DOCKER_HOST_IP}"
#    networks:
#      - backend

  test-web:
    image: "${COMPOSE_PROJECT_NAME}/${STAGE}/web:${BRANCH}"
    volumes:
      - ./test-web:${WEB_CONTAINER_PATH}
    networks:
      - frontend

  ### Docker-in-Docker ################################################
  docker-in-docker:
    image: docker:dind
    privileged: true
    volumes:
      - ${API_SOURCE_PATH}:${API_CONTAINER_PATH}
      - ${DATA_PATH_HOST}/dind:/var/lib/docker
    expose:
      - 2375
    networks:
      - backend
